services:
  backend:
    container_name: backend-faq
    restart: unless-stopped
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - ENVIRONMENT=production
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000

    depends_on:
      - db
      - redis
      - chroma
    volumes:
      - ./data:/app/data
    networks:
      - smart-task-network

  chroma:
    container_name: chroma-faq
    image: chromadb/chroma:latest
    restart: unless-stopped
    environment:
      - IS_PERSISTENT=TRUE
    volumes:
      - ./data/chroma:/data
    networks:
      - smart-task-network

  db:
    container_name: postgres-faq
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - smart-task-network

  redis:
    container_name: redis-faq
    restart: unless-stopped
    image: redis:7-alpine
    networks:
      - smart-task-network
    ports:
      - "6379:6379"

  adminer:
    container_name: adminer-faq
    image: adminer
    restart: unless-stopped
    networks:
      - smart-task-network
    depends_on:
      - db
    ports:
      - "8089:8080"

volumes:
  pgdata:

networks:
  smart-task-network:
    external: true